apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv-efk
  namespace: efk
  annotations:
    #pv.beta.kubernetes.io/gid: "590"
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-ep-efk
    path: efk_shared
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
